### ISSUE TITLE
Invisible armor

### ISSUE THREAD

**Issue by Kuggle01** [MoriyaShiine/bewitchment#267] opened 2022-03-22 03:03 UTC
![Minecraft_ 1 18 1 - Singleplayer 3_21_2022 10_08_05 PM (2)](https://user-images.githubusercontent.com/77563171/159399285-b1c8c138-d544-4f32-9d92-1d4a0d422913.png)
The HedgeWitch armor renders invisible. I'm not sure what is causing it, I do have a few mods that affect rendering like sodium and indium, I've tried disabling every mod I know of that affects rendering to no avail. I haven't tested with the other witch armors but I imagine it's the same. I'm using version 1.18-15 of the mod and this is the modpack I'm using https://drive.google.com/file/d/16lum5SmoefIH3v_pWkQa4OH8HN-T652E/view?usp=sharing
Drive link because I built the modpack myself

**Comment by MoriyaShiine** [comment] 2022-03-23 17:39
Does it still happen in 1.18.2?

**Comment by Kuggle01** [comment] 2022-03-23 19:54
Not sure, Can't update to 1.18.2 yet since most of the mods I want in my modpack are still in 1.18.1

**Comment by MoriyaShiine** [comment] 2022-03-23 19:56
I'll close this then as I can't reproduce it on the current latest version (1.18-16). You can reopen the issue if you find what mod causes it

**Closed by MoriyaShiine** 2022-03-23 19:56 UTC
