### ISSUE TITLE
Magic Energy bar not appearing

### ISSUE THREAD

**Issue by slammaja** [MoriyaShiine/bewitchment#336] opened 2022-12-24 12:28 UTC
### Mod version

1.18-23

### A description of the issue

As stated in title, no matter what I do, the bar just won't appear. It's probably conflicting with some other mod in my pack. Any idea what kind of mods could be interfering with this gui element?
![2022-12-24_13 21 07](https://user-images.githubusercontent.com/12775695/209436242-42ce012c-d48c-4727-b27f-d2c2b2c7df19.png)

**Comment by MoriyaShiine** [comment] 2022-12-24 12:30
If you mean the bar on the left, it only appears when its value changes

**Comment by slammaja** [comment] 2022-12-24 13:28
I know, but it doesn't do that. It just never appears.

**Comment by MoriyaShiine** [comment] 2022-12-24 13:40
I'd need a mod list then, ideally the whole log file

**Comment by slammaja** [comment] 2022-12-24 13:45
[latest.log](https://github.com/MoriyaShiine/bewitchment/files/10298681/latest.log)

**Comment by MoriyaShiine** [comment] 2023-05-09 23:09
Gonna close this for now since I can't reproduce, but if it still persists then it can be reopened

**Closed by MoriyaShiine** 2023-05-09 23:09 UTC
