### ISSUE TITLE
Familiar and sever ritual not working properly/ Werewolf bug

### ISSUE THREAD

**Issue by achein12** [MoriyaShiine/bewitchment#48] opened 2021-03-06 20:35 UTC
When I use the familiar ritual for my tamed raven or it works only a few seconds then spits out the items doing nothing, I increased the power of the alter to 1500 and still does the same. The same problem happens when I use the sever ritual thinking I have the familiar.

Werewolf problem;
I cant get rid of the werewolf curse when I present Herne with the aconite flower and if I eat garlic I get weakness, slowed and hunger, I dont know if that is supposed to happen.
Hope you can find this issue thanks, love the mod so far.

**Comment by Aelpecyem** [comment] 2021-03-06 20:39
First of all, you should split different issues and not put them into one.

Second, the other part of the issue has just been fixed in https://github.com/MoriyaShiine/bewitchment/commit/693be77e70136a595596680854d1a2501d7616b9

**Comment by Aelpecyem** [comment] 2021-03-06 20:41
I can't reproduce the familiar issue you're describing, so I'll just assume you did something wrong.
Is the taglock of the raven? Is the entity loaded? Do you already have a familiar somewhere? If you had one before and it died, that may tie to https://github.com/MoriyaShiine/bewitchment/commit/ba86df786e1b324ec9c658a00de2c1ae5d0e8a0c

**Comment by achein12** [comment] 2021-03-06 20:41
Ok, Sorry will do in the future and thank you!!

**Comment by achein12** [comment] 2021-03-06 20:42
Am I supposed to use the taglock on the raven or is it my taglock?

**Comment by Aelpecyem** [comment] 2021-03-06 20:44
The taglock must be that of your tamed raven, and you have to be close to the circle

**Comment by achein12** [comment] 2021-03-06 20:46
Oh ok ill check now if it works.

**Comment by achein12** [comment] 2021-03-06 20:47
I cant taglock the tamed raven

**Comment by Aelpecyem** [comment] 2021-03-06 20:49
you can taglock things by hitting them

**Comment by achein12** [comment] 2021-03-06 20:50
Ah ok, didnt know that thank you now it works.

**Comment by Aelpecyem** [comment] 2021-03-06 20:51
@MoriyaShiine close pls k thanks

**Closed** 2021-03-06 21:01 UTC
