### ISSUE TITLE
Scaffolding crashes game w/ Sodium and Bewitchment.

### ISSUE THREAD

**Issue by enigmaticectasy** [MoriyaShiine/bewitchment#76] opened 2021-03-26 21:23 UTC
Placing around 13-14 scaffolding crashes the game with BOTH sodium and bewitchment and it's dependencies downloaded. Not sure if i have anything wrong in the modlist with bewitchment, but the modlist i'm using that crashes is:
- bewitchment-1.16.5-8
- cloth-config-4.11.15-fabric
- fabric-api-0.32.5+1.16
- Impersonate-2.1.0
- Patchouli-1.16.4-50-FABRIC
- Pehkui-1.9.0+21w10a
- sodium-fabric-mc1.16.3-0.1.0
- somnus-fabric-0.0.11-1.16.5
- trinkets-2.6.7

Removing either sodium or bewitchment causes the crash to stop, and even if scaffoldings do not crash the game (rarely), they tend to not be loaded in. 

Apologies if i'm missing anything here, kind of my first time doing a report on anything, please let me know if i need to post something :)

**Comment by DevArcana** [comment] 2021-03-29 14:27
I did some testing too, the problem is this:

```
Exception in thread "Chunk Render Task Executor #19" [16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index -152 out of bounds for length 5832
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.world.WorldSlice.getBlockState(WorldSlice.java:232)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.handler$bei000$getCollisionShape(AbstractBlock.java:2067)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.getCollisionShape(AbstractBlock.java)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.getCollisionShape(AbstractBlock.java:793)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.isFullCube(AbstractBlock.java:985)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.AbstractBlock.getAmbientOcclusionLightLevel(AbstractBlock.java:304)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.getAmbientOcclusionLightLevel(AbstractBlock.java:723)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess.compute(LightDataAccess.java:67)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.cache.ArrayLightDataCache.get(ArrayLightDataCache.java:56)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.AoFaceData.initLightData(AoFaceData.java:37)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.getCachedFaceData(SmoothLightPipeline.java:182)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyAlignedPartialFace(SmoothLightPipeline.java:151)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyComplex(SmoothLightPipeline.java:114)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:81)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:102)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:73)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.renderBlock(ChunkRenderContext.java:43)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:93)
[16:24:46] [Chunk Render Task Executor #19/INFO] (Minecraft) [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:347)
```

This looks like a Sodium problem and not BW. Can anyone confirm this?

**Comment by DevArcana** [comment] 2021-03-29 14:32
Ok, I identified the problem.
```
client.ClientWorldMixin
```

This mixin conflicts with Sodium.

**Comment by DevArcana** [comment] 2021-03-29 15:15
One last update from me. I tried debugging Sodium instead. Had to update it to 1.16.5 and newest Fabric loader. Somehow that fixed the problem so I guess that the fix was introduced at one point to the master branch but isn't released yet. I guess the issue is not related to BW strictly. Still no clue why it would even occur with BW installed though. For those impatient, just build Sodium from sources and use that temporarily. Not sure how stable that is though.

**Comment by Aelpecyem** [comment] 2021-03-29 15:54
Ok, I tested it with the very latest sodium build straight from source and it's definitely not an issue anymore
I think it's safe to close this issue now and wait for a public release on curseforge

**Closed** 2021-03-29 15:56 UTC
