### ISSUE TITLE
Strange behavior on server

### ISSUE THREAD

**Issue by ZroNoh** [MoriyaShiine/bewitchment#168] opened 2021-07-28 03:34 UTC
None of this happens when in single player which is the odd part. I am running Bewitchment 1.16.5-18 but this issue has gone back to 1.16.5-16. I haven't tested any other versions.

Player ME will not charge and the meter stays on the side at all times no matter what
![java_t7rhEK4awZ](https://user-images.githubusercontent.com/32776743/127259013-9724dfcc-949f-49e8-8630-7c6085f40e25.png)

Brooms are not flyable even with an owl familiar
![java_PzPHAVIrt6](https://user-images.githubusercontent.com/32776743/127259145-1bc49939-6f8e-4019-897a-076a97411903.png)

Werewolves are just stretched humans.
![brave_XIuhsQl9lM](https://user-images.githubusercontent.com/32776743/127259233-c6e814a8-dfc1-4824-a750-0676b38707c0.png)

https://mclo.gs/CwvmiOL

**Comment by VoidLock92** [comment] 2021-07-28 06:06
What is your server view distance set to in the server properties?

**Comment by ZroNoh** [comment] 2021-07-28 06:37
> What is your server view distance set to in the server properties? #161 Maybe this could help you, I spent a lot of time researching and debugging this to see what was causing it on my end.

I have mine set to 10 currently

**Comment by VoidLock92** [comment] 2021-07-28 07:02
Just out of curiosity, can you post a list of mods separated by client side and server side? Also try setting your view distance just to see, that's what I set my server to and the issue went away.

**Comment by ZroNoh** [comment] 2021-07-28 18:58
I tried setting my view distance to 8, but no luck.

Here's my mod list but I may have missed some when separating the client and server mods.
https://pastebin.com/fbneDRBq
I have all of these on the files for my server, I could try removing the client ones but afaik they don't get loaded on servers anyway.

**Comment by VoidLock92** [comment] 2021-07-28 20:48
Ohh yeah that's a hefty list. I would start with trying to see what is causing a memory leak. I use VisualVM to monitor memory usage and such, it can help narrow down a leak. I found that in my case the issue was caused by a memory leak. AdventureZ has a small one in version 1.16.5 that was fixed in 1.17+ it was caused by the mammoths. So anything even that small can cause an issue like desync. 

If your issue is not caused by desync then it will be because of mod incompatibility I would assume. If all else fails, what I did also was make a copy of the entire pack onto a test server and just have Bewitchment and its required mods, test it and see if you have the issue. Then to go from there I would add them back in one at a time doing a test in between each added mod. Realistically I add them back in batches of 3-4 at a time then if that batch caused issue you can narrow it down to what in that batch caused it.

Never the less in my experience the desync issue is caused by a memory leak of some sort on the server which keeps the server in a constant state of desync.

How much ram did you dedicate to the server? Do you use a startup .BAT file to start the server? If so what java parameters are you using? Once we know this I would suggest using VisualVM and monitoring the ram usage over the course of several hours and see if the total ram slowly gets eaten up over time. This would point to a memory leak on your server.

**Comment by ZroNoh** [comment] 2021-07-28 21:28
The server isn't self hosted since I only have a DSL connection so I'm hosting it on server miner. It's currently running 4GB of ram. Which has been enough so far as it normally runs around 40% usage with 7 players online. I'll try to look for a mod incompatibility though.

**Comment by MoriyaShiine** [comment] 2021-07-28 21:40
I don't think it's a mod interaction, it's just data tracker jankery. I'll attempt to fix it once 1.17 is ready, which is soon

**Closed** 2021-07-30 18:04 UTC
